const galleryConfig = {
  // This file is automatically generated by update_gallery.ps1
  // Do not edit the image list manually if you plan to use the script.

  title: "My Trendy Gallery",

  images: [
    "arch.png",
    "neon.png",
    "street.png",
    "신창섭.jpg",
    "신창섭2.jpg",
    "신창섭3.jpg",
    "신창섭4.jpg",
    "신창섭5.jpg",
    "신창섭6.jpg",
    "신창섭7.jpg",
    "신창섭8.jpg",
    "신창섭9.jpg",
    "facereview-logo.svg",
    "logo.svg"
  ]
};
